// GET API for transactions for every month

GET http://localhost:3000/transactions?month=july

###

// GET API for statistics for every month
GET http://localhost:3000/statistics?month=march

###

// GET API for bar-chart for every month
GET http://localhost:3000/bar-chart?month=march

###

// GET API for pie-chart for every month
GET http://localhost:3000/pie-chart?month=march

###

// GET API for combined-response for every month
GET http://localhost:3000/combined-response?month=march

###
